### ISSUE TITLE
_extract_data_from_ses_signal error

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#1024]
From beta.  Maybe old:
```
[27/Jun/2022 13:40:57,634] ERROR[views.py:1168 (_extract_data_from_ses_signal)] Error extracting data from comments header : App 'topicblog' doesn't have a 'SendRecordTransactionalEmail' model.

[23/Nov/2022 08:53:28,778] ERROR[views.py:1321 (send_received_handler)] Error while updating send_record : SendRecordTransactionalEmail matching query does not exist

```

**Comment by Shriukan33** [comment]
The dev mails I send to myself are going through AWS, that causes a mismatch between the send records : those I have locally and those on beta. 
So when I send an email, it's say ID = 200, while beta doesn't have this ID, but receives the AWS signal. 
So it's not an actual issue, it's just because of my test emails.

**Comment by JeffAbrahamson** [comment]
Are the errors incorrect then?  Can we log better?

**Comment by Shriukan33** [comment]
The thing is that I use the beta credentials to send myself emails (send to myself button, mobilito sessions) while using my local database. 

So locally I create send records. But beta receives the AWS signals that cascade from it. 
When I create the email, I add in the AWS header the sendrecord_id (which is in my local db), which is then read by beta's signal receiver. The sendrecord I have in my db isn't in beta's, and beta is confused because it can't update the send record the signal is referring to !

About the logging we could check the role (!"production") to ignore those, because they are expected. Or just ignore them on beta logs.
We should totally be worried if those logs showed to production, because it would be a different problem then !

**Comment by JeffAbrahamson** [comment]
Right, and this is why chasing small errors is the right thing to do: because if they get big, you now have two problems.

What if you just created your own SES keys on your own AWS account?  You'd assuredly fall well below the limit where any charges are incurred.

If we adopt a policy that only beta uses beta keys and only prod uses prod keys, that solves the problem.
