### ISSUE TITLE
Test that we don't serve unpublished or non-servable TBItems

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#245]
Recall:
* We make an item publishable so that it may be served.  For now, only admins should be able to do that (in the admin interface, until we create a button).  This can not be undone.
* We mark them non-servable at EOL.  This _can_ be undone.

**Comment by Shriukan33** [comment]
For a bit of precision, we don't serve servable but unpublished items ?
We already discussed the whole servable / published issue on Slack, it's just been a while and lots happened in the meantime so I want to make sure. 


* Servable = True / Published = True / publication_date = Not None --> We load the item and display it no problem on the website. 
* Servable = True / Published = **False** / publication_date = Not None  --> Shouldn't happen because published can't be reversed to False. 
* Servable = True / Published = False / publication_date = **None** --> Raises 404 ?

* Servable = False / Published = True / publication_date = Not None --> We raise a 404 error on the attempt. This content shouldn't be accessible anymore. 
* Servable = False / Published = **False** / publication_date = Not None --> Can't happen either, .publish() function does set a time on the publication_date field when it turns published to True, and can't be reverted later. 
* Servable = False / Published = **False** / publication_date = None --> Default state of a content, raises a 404.

So by examining all that we can see that the _only_ combination that leads to be accessible by the public is Servable = True / Published = true and / publication_date = Not None. 
So once, again, what's the point of keeping "published" attribute when we can check if the publication date is not None or None ?

**Comment by JeffAbrahamson** [comment]
You're confused.  And "can't happen" is "shouldn't happen", you always have to handle the case.

* `servable` is set true at beginning of life, can become false.
* `published` is set false at beginning of life, can be set true.  Can be toggled if needed.
* `publication_date` is spec'd to be None (SQL: NONE) if `not published`, a real date otherwise.  Possibly in the future.  We should set it on first publication.  It could be modified to the future but not to the past (but to less than the future is surely ok).

And all of this probably happens at the time that you query for pages.  So
```
TopicBlogItems.filter(servable=True, published=True, slug=slug).having_max(item_sort_index)
```
where I've made up the function "having_max" because I don't have the right formulation in my head.

If you needed code, say to show on a web page to admins whether or not a age could be served, it would look like this:
```
def get_servable_status(self):
    """Return True if page is user visible, False otherwise."""
    if not self.servable:
        return False
    if not self.published:
        return False
    if datetime.datetime.now() < self.publication_date:
        return False
    return True
```

**Comment by JeffAbrahamson** [comment]
And, yes, removing the boolean `published` is probably fine.  I think I suggested that once upon a time and you came up with a reason (that I've forgotten but that you apparently didn't document in the code ;-) ) that we should keep it.

**Comment by Shriukan33** [comment]
> And, yes, removing the boolean `published` is probably fine. I think I suggested that once upon a time and you came up with a reason (that I've forgotten but that you apparently didn't document in the code ;-) that we should keep it.

Found the related conversation : 
![image](https://user-images.githubusercontent.com/70256364/141979141-a4099896-1b84-4e04-92aa-643b044d48a2.png)
![image](https://user-images.githubusercontent.com/70256364/141979158-9cfa30d5-b1b2-4f84-8bd2-315342ae9e19.png)
![image](https://user-images.githubusercontent.com/70256364/141979184-afe46ddc-8100-4d79-a588-ba57b671c24c.png)

So it appears that we agreed that we would only have `servable` as a bool, and `publication_date` that would be the control to see if something is published or not : `If publication_date is none`, it's not published, otherwise it's published. 

For the check on what's displayed on the site, we check that both conditions : `servable == True and publication_date is not None`

Sounds good ?

**Comment by JeffAbrahamson** [comment]
Yeah, I'm ok with that.  If you accidentally publish something, you can fiddle with the date so that it isn't shown.  And None / NULL for not yet published.

And so the query stays something like
```
TopicBlogItems.filter(
    servable=True, publication_date is not None, slug=slug).having_max(
    item_sort_index)
```

and the function something like
```
def get_servable_status(self):
    """Return True if page is user visible, False otherwise."""
    if not self.servable:
        return False
    if self.publicatin_date is None or datetime.datetime.now() < self.publication_date:
        return False
    return True
```

**Comment by Shriukan33** [comment]
LGTM

**Comment by JeffAbrahamson** [comment]
I think you mean SGTM. ;-)
