### ISSUE TITLE
Capture failed and abandoned payment events

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#247]
and record them in the donations table as such

**Comment by Shriukan33** [comment]
What sort of information you want in this ? Amount to 0 ? 

This is what we get : https://dashboard.stripe.com/events/evt_3JlzmlClnCBJWy551J9gP13a

```json
{
  "object": {
    "id": "pi_3JlzmlClnCBJWy551tj0Ofri",
    "object": "payment_intent",
    "amount": 500,
    "amount_capturable": 0,
    "amount_received": 0,
    "application": null,
    "application_fee_amount": null,
    "canceled_at": 1634665090,
    "cancellation_reason": "automatic",
    "capture_method": "automatic",
    "charges": {
      "object": "list",
      "data": [
      ],
      "has_more": false,
      "total_count": 0,
      "url": "/v1/charges?payment_intent=pi_3JlzmlClnCBJWy551tj0Ofri"
    },
    "client_secret": "pi_3JlzmlClnCBJWy551tj0Ofri_secret_wpUXvwgWPodGgiaN9LjGlgBap",
    "confirmation_method": "automatic",
    "created": 1634578687,
    "currency": "eur",
    "customer": null,
    "description": null,
    "invoice": null,
    "last_payment_error": null,
    "livemode": true,
    "metadata": {
    },
    "next_action": null,
    "on_behalf_of": null,
    "payment_method": null,
    "payment_method_options": {
      "card": {
        "installments": null,
        "network": null,
        "request_three_d_secure": "automatic"
      }
    },
    "payment_method_types": [
      "card"
    ],
    "receipt_email": null,
    "review": null,
    "setup_future_usage": null,
    "shipping": null,
    "source": null,
    "statement_descriptor": null,
    "statement_descriptor_suffix": null,
    "status": "canceled",
    "transfer_data": null,
    "transfer_group": null
  }
}
```

We also get, if this has gone through a Checkout Session the checkout.session.expired event, that happens 24h after the creation of the checkout session. 
this means that someone that get to payment page on Stripe can close the tab and get back to it up to 24h after its creation. 

Details of the event : https://dashboard.stripe.com/events/evt_1JmMGMClnCBJWy55LtFqT7cD

I'm not going to paste it here because it has identifying information.

**Comment by Shriukan33** [comment]
What sort of information you want in this ? Amount to 0 ? 

This is what we get : https://dashboard.stripe.com/events/evt_3JlzmlClnCBJWy551J9gP13a

```json
{
  "object": {
    "id": "pi_3JlzmlClnCBJWy551tj0Ofri",
    "object": "payment_intent",
    "amount": 500,
    "amount_capturable": 0,
    "amount_received": 0,
    "application": null,
    "application_fee_amount": null,
    "canceled_at": 1634665090,
    "cancellation_reason": "automatic",
    "capture_method": "automatic",
    "charges": {
      "object": "list",
      "data": [
      ],
      "has_more": false,
      "total_count": 0,
      "url": "/v1/charges?payment_intent=pi_3JlzmlClnCBJWy551tj0Ofri"
    },
    "client_secret": "x",
    "confirmation_method": "automatic",
    "created": 1634578687,
    "currency": "eur",
    "customer": null,
    "description": null,
    "invoice": null,
    "last_payment_error": null,
    "livemode": true,
    "metadata": {
    },
    "next_action": null,
    "on_behalf_of": null,
    "payment_method": null,
    "payment_method_options": {
      "card": {
        "installments": null,
        "network": null,
        "request_three_d_secure": "automatic"
      }
    },
    "payment_method_types": [
      "card"
    ],
    "receipt_email": null,
    "review": null,
    "setup_future_usage": null,
    "shipping": null,
    "source": null,
    "statement_descriptor": null,
    "statement_descriptor_suffix": null,
    "status": "canceled",
    "transfer_data": null,
    "transfer_group": null
  }
}
```

We also get, if this has gone through a Checkout Session the checkout.session.expired event, that happens 24h after the creation of the checkout session. 
this means that someone that get to payment page on Stripe can close the tab and get back to it up to 24h after its creation. 

Details of the event : https://dashboard.stripe.com/events/evt_1JmMGMClnCBJWy55LtFqT7cD

I'm not going to paste it here because it has identifying information.

**Comment by JeffAbrahamson** [comment]
If I understand correctly, this is a cancellation event that we receive if the user times out or cancels the transaction.  We've never received an event about this person starting to pay, so there's never been an indication of their paying 5 €.  Is that correct?

If so, I'd say we should capture all the usual stuff for a payment but record an amount field of zero.  And we should note in the model that we record zero for cancelled payments.

Why?  Because (eventually, when we get better at communicating with people) we should surely send a mail saying "hey, thanks for thinking of donating, we're sorry you didn't, if you meant to, here's a link, if you meant to abandon, tell us why, and BTW here's some information on what we're up to and why we're worth your donation".

Wdyt?

**Comment by Shriukan33** [comment]
> If I understand correctly, this is a cancellation event that we receive if the user times out or cancels the transaction. We've never received an event about this person starting to pay, so there's never been an indication of their paying 5 €. Is that correct?
> 
> If so, I'd say we should capture all the usual stuff for a payment but record an amount field of zero. And we should note in the model that we record zero for cancelled payments.
> 
> Why? Because (eventually, when we get better at communicating with people) we should surely send a mail saying "hey, thanks for thinking of donating, we're sorry you didn't, if you meant to, here's a link, if you meant to abandon, tell us why, and BTW here's some information on what we're up to and why we're worth your donation".
> 
> Wdyt?

Sounds good
