### ISSUE TITLE
Extend JS slugifier to CTA slugs

### ISSUE THREAD

**Issue by Shriukan33** [transport-nantes/tn_web#265]
CTA slugs don't enforce slug on the fly, to the contrary of the item's slug.

**Comment by Shriukan33** [comment]
* Will we always want all slugs to be discoverable?  What if some slugs correspond to restricted content, for example?  This code would enforce a requirement that slug names not leak content on restricted pages.

_Originally posted by @JeffAbrahamson in https://github.com/transport-nantes/tn_web/issues/291#issuecomment-970073916_

Following this comment, we need to figure out how to flag slugs we don't want to appear. 

What slugs we don't want to be available on TBIEdit form ?

**Comment by JeffAbrahamson** [comment]
Consider a slug for an article with content restricted to staff and board members.  We don't currently have any sort of permissioning, but it's inevitable that that will grow into the system at some point.

In retrospect, this probably isn't the main issue, since we could filter that as easily in the view as in an ajax endpoint.  My real concern is that we make the initial page load heavy and cache-incompatible by pre-loading all slugs.

**Comment by Shriukan33** [comment]
> Consider a slug for an article with content restricted to staff and board members. We don't currently have any sort of permissioning, but it's inevitable that that will grow into the system at some point.
> 
> In retrospect, this probably isn't the main issue, since we could filter that as easily in the view as in an ajax endpoint. My real concern is that we make the initial page load heavy and cache-incompatible by pre-loading all slugs.

The easiest way would probably be bools to check if this is for Staff and more or Admins only, then check the value of those before loading the item in get(). 



> In retrospect, this probably isn't the main issue, since we could filter that as easily in the view as in an ajax endpoint. My real concern is that we make the initial page load heavy and cache-incompatible by pre-loading all slugs.

So this isn't a priority, maybe let's not try to solve a problem we don't have with those limited access and see what the future holds. 

I'm going to implement that Ajax query for longer inputs so it doesn't load all slugs at once.

**Comment by JeffAbrahamson** [comment]
Cool.  I'd suggest not suggesting until you have a few characters just to maintain responsiveness.  Probably also limit search results to 20 or so (sorted by publish date descending as a proxy for relevance?).

**Comment by JeffAbrahamson** [comment]
LOL, yeah, you should definitely do distinct.  A suggestion list with 10 times a single slug would be pretty egg-on-face embarrassing. ;-)

**Comment by JeffAbrahamson** [comment]
You have no guarantee that primary keys are assigned in order, although it may happen to be true for the current version of the current database.  Thus my suggestion to use pub date.

**Comment by JeffAbrahamson** [comment]
You could just do `distinct()`, since you're selecting only one field anyway.

**Comment by JeffAbrahamson** [comment]
The `set` is a clever work-around, but in general when dealing with SQL you should try to make the database do your work for you.  The risk here is that as we start using these features (assuming we do...) you'll get differing lengths, maybe by quite a lot.  Ask the db to do the distinct for you rather than working around it.
