### ISSUE TITLE
Decay to hamburger gracefully

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#284]
At too many image resolutions, we could show _something_ but instead show nothing.  Perhaps we can do better.

![image](https://user-images.githubusercontent.com/1220683/141693518-658d3866-f639-4787-b1d6-4d21c41cf2c0.png)

**Comment by Shriukan33** [comment]
Okay so I went on and checked what others do, because I'm not exactly great at coming with great designs yet ! :D 

So Greenpeace : 
* Hamburger is always present
* Remains the donation button
* Collapses at 1014 px : 
![image](https://user-images.githubusercontent.com/70256364/142410980-11983221-4855-4a54-bbad-4fbedee297fa.png)
![image](https://user-images.githubusercontent.com/70256364/142411038-4b69656e-c4bc-49ea-a146-5341f1872834.png)

Amnesty : (To come, will edit, time to eat just so hungry)

**Comment by JeffAbrahamson** [comment]
What is the status here?

It remains the case that visitors to our site with medium screens see a vast blank menu and no invitation to click on the first screenful of text.

**Comment by Shriukan33** [comment]
Maybe we should ask @GaelleMobilitains  her opinion on the navbar, maybe there is something we can do with it

**Comment by Shriukan33** [comment]
Status update : Gaelle has seen this and I reminded her this task on the 20th. 

I specified it wasn't a very high priority to her, as we already have plenty to deal with.

**Comment by JeffAbrahamson** [comment]
If we have space for two things, we should have a menu [nos projets] pointing to [la grande mobilité, la petite mobilité, vélopolitain, -, qui sommes nous].  And a button "faire un don".

If we are somewhat space constrained, we should have a hamburger with the word "menu" to its left.

If we are really space constrained (mobile), we should just show the hamburger.

In all cases, our logo and name stays on the right by itself.

The danger zone where we've been doing badly is somewhere in the 750-900 pixel wide range.
