### ISSUE TITLE
timing bug with publication model

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#331]
We had the clever idea to create variants vs simply resaving TBItems.

And we had the quite reasonable goal of maintaining controls on publication, so that someone authorised to modify an article might need a second LGTM to publish it.

An unintended side-effect of this is that if X modifies a TBItem that is the only servable instance of that slug, then the servable instance is immediately marked unservable whereas the new items is not yet servable (because not yet published).  So that's a bug.

Maintaining a concept of "articles to retire when this one is published" introduces quite a lot of complexity to get right for very little benefit.  So I'm quite hesitant to go that route.

I think the simplest thing is simply to let the new item be unpublished.  You see the article immediately now (on PR 329) so it's easy enough to act on.  And after publication, you can retire the old one or not as you see fit.  The link to do so is shown in the control header.

_Aside: There are still issues with retirement.  The primary blocking issue is how to handle retiring the sole servable instance of a slug.  This isn't urgent today._

**Comment by Shriukan33** [comment]
Trying to make it clear : 
So for now you say that when a servable item (that has been published) is being issued a variant (copy), it sets the item's `servable=False` and make the page unpublished. 

This happens here : https://github.com/transport-nantes/tn_web/blob/4b9be357475cceacd906425c667c61b475abe98c/transport_nantes/topicblog/views.py#L104

When you click "Sauvegarder", the form_valid() function will make unservable the item you sent through your post request. 

Idea would be to remove that line, correct ? Doing so, you would save in place the changes, before creating a variant with another pk. Note that variant would also be servable unless we decide otherwise, I just want to make clear your intentions. :slightly_smiling_face:

**Comment by Shriukan33** [comment]
@JeffAbrahamson  As we progressed with TBv2 with the list view, what's your input on this issue ? I struggle to see the exact description on the problem here beside it's still not yet possible to retire a content? I hardly see what you mean with timing bug now

**Comment by JeffAbrahamson** [comment]
Well, I think we've slowly evolved into something where "variant" doesn't even make a lot of sense any more.  We'd talked about save / save as draft / preview / cancel.  But it's becoming clear that the first three are all the same: save something and redirect to viewing it.  None of these things unpublishes anything.  Indeed, I think we should move to a model where no one is allowed to self-publish: you always need an LGTM provided by someone else clicking the publish button.

We might store the user id of the creator and of the publisher at that point.

The current issue is just removing the unpublish, because if you edit, say, index, and save it, you will render the root page unservable.

**Comment by JeffAbrahamson** [comment]
(and you've correctly identified the LOC in question)
