### ISSUE TITLE
Make navbar sticky

### ISSUE THREAD

**Issue by Shriukan33** [transport-nantes/tn_web#412]
From @GaelleMobilitains 
The navbar disappears too fast and visitors don't have the time to consider either the menu or the donate button.

**Comment by JeffAbrahamson** [comment]
As noted in slack, I'm largely against making the navbar sticky.  I'd want good evidence that it has some effect and to test that that evidence is true.

It only disappears because the user scrolls, and the user scrolls to see what's below.  Eating a big chunk of the top of the screen is just getting in the way.
