### ISSUE TITLE
Add pagination (press app : listview)

### ISSUE THREAD

**Issue by mcmikashi** [transport-nantes/tn_web#492]
Add pagination to the listview.

**Comment by JeffAbrahamson** [comment]
Not more, but next page of.  Think "what happens if there are 10x the entries?  100x?".  What would it do to bandwidth usage and db load if the user clicks more a few times and starts pulling 10K lines on request?  And then shares that URL?

Here's an example:

![image](https://user-images.githubusercontent.com/1220683/154644425-a380bf96-0929-4246-9d20-50bdf5a13234.png)

Here's another:

![image](https://user-images.githubusercontent.com/1220683/154644692-2c3fd9ae-f1d6-4916-8a32-a4ad622d7c87.png)

Django calls this pagination, I think.  Some resources:
* [mozilla](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Generic_views)
* [djangoproject](https://docs.djangoproject.com/en/3.2/ref/class-based-views/generic-display/#listview)
* [SO](https://stackoverflow.com/questions/57861249/pagination-with-listview-django)
