### ISSUE TITLE
stripe donation does not always set user name correctly

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#733]
Stripe donations should set the users first and last name if they are both not set.  If either is set, it should not.

Yet that doesn't always happen.  For example, the user associated with donation 11, who has first and last name, has user id 118 and empty first and last names.

Here I'm looking at data on beta.

**Comment by Shriukan33** [comment]
I've looked into it, it's because their profile was created before we matched donations and users ( 9888f39a3d9f43aabfa4ced631f4f8da5d9b378e ) 
The subscription_cycle event doesn't have metadata that contain first name and last names (while checkout event does)
It has a single field "customer name" that doesn't split first and last name, and parsing it could be tricky.

As it's a single occurrence I think we could fill it manually and let the update_user_name function does its job, moving forward. :slightly_smiling_face:

**Comment by JeffAbrahamson** [comment]
Sure, if this is already fixed, let's close this.
