### ISSUE TITLE
Add map to mobilito session reports

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#981]

**Comment by Shriukan33** [comment]
No assignees, are you handling it ?

Otherwise, what do you mean by map ? An actual embedded map on the web visualization ?

**Comment by Shriukan33** [comment]
Should this map appear in the email summary as well ? That would mean we need to generate a PNG from a map, which can complicate things.

I don't think we should aim to get everything in the mail given the complexity layer it adds, simply incentivize clicking on the web version button, at least for now.

**Comment by Shriukan33** [comment]
I did some research about how to go from lat/lng tuple to rendered png, there are services that provide that but it looks quite complex and long for that purpose. 

https://print.get-map.org/about/api/
https://github.com/hholzgra/ocitysmap/

Or maybe having a tile render server of our own 
https://github.com/enzet/map-machine#tile-server

There is no easy way if we want to add that into emails, I think.
Maybe we should encourage clicking to discover more info about the session, instead of trying to render it before sending. That would be much simpler implementation wise, not sure this is worth the hassle. 

What do you think ?
